package br.com.transporteEscolar.controller;

import br.com.transporteEscolar.model.Onibus;
import br.com.transporteEscolar.repository.OnibusRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.Optional;

//import br.com.transporteEscolar.repository.OnibusRepositoryJPA;

@CrossOrigin // anotação para que a api receber chamadas de aplicações externas
@RestController // anotação que determina que é um REST This means that this class is a Controller
@RequestMapping(path="/api/onibus") // This means URL's start with /demo (after Application path)
public class OnibusController {

    @Autowired // Cria e abre uma conexão com banco pra quando for,
                // necessario chamar alguma funcionalidade do repositorio
    // Which is auto-generated by Spring, we will use it to handle the data
    private OnibusRepository onibusRepository;

    @GetMapping(path="/all", produces= MediaType.APPLICATION_JSON_VALUE)
    public @ResponseBody Iterable<Onibus> getAllOnibus()
    {
        return onibusRepository.findAll();
    }

    @RequestMapping(value="/get/{id}", method=RequestMethod.GET)
    public @ResponseBody
    Optional<Onibus> getOnibusByI(@PathVariable(name = "id") long id) {

        return onibusRepository.findById(id);
    }

    // -------------------Criar Onibus-------------------------------------------

    @PostMapping("/add")
    protected @Valid Onibus addOnibus(@Valid @RequestBody Onibus onibus) {

        return onibusRepository.save(onibus);

    }

    // ------------------- Update Onibus ------------------------------------------------

    @PutMapping(value = "/edit")
    protected @Valid Onibus editOnibus(@Valid @RequestBody Onibus onibus) {

        return onibusRepository.save(onibus);
    }

}